//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	islandoraModel "github.com/lehigh-university-libraries/go-islandora/model"
)

// IslandoraObject defines model for IslandoraObject.
type IslandoraObject struct {
	Changed                    *islandoraModel.GenericField         `json:"changed,omitempty"`
	Created                    *islandoraModel.GenericField         `json:"created,omitempty"`
	FieldAbstract              *islandoraModel.TypedTextField       `json:"field_abstract,omitempty"`
	FieldAccess                *islandoraModel.GenericField         `json:"field_access,omitempty"`
	FieldAffiliatedInstitution *islandoraModel.EntityReferenceField `json:"field_affiliated_institution,omitempty"`
	FieldAltTitle              *islandoraModel.GenericField         `json:"field_alt_title,omitempty"`
	FieldClassification        *islandoraModel.GenericField         `json:"field_classification,omitempty"`
	FieldCollectionHierarchy   *islandoraModel.EntityReferenceField `json:"field_collection_hierarchy,omitempty"`
	FieldCoordinates           *islandoraModel.GeoLocationField     `json:"field_coordinates,omitempty"`
	FieldCoordinatesText       *islandoraModel.GenericField         `json:"field_coordinates_text,omitempty"`

	// FieldCopyrightDate Date of copyright of the resource.
	FieldCopyrightDate      *islandoraModel.EdtfField            `json:"field_copyright_date,omitempty"`
	FieldCreatorDescription *islandoraModel.GenericField         `json:"field_creator_description,omitempty"`
	FieldCreatorEmail       *islandoraModel.EmailField           `json:"field_creator_email,omitempty"`
	FieldCreatorRole        *islandoraModel.EntityReferenceField `json:"field_creator_role,omitempty"`

	// FieldDateModified Date on which the original resource being represented in Islandora was changed. Typically modification dates of digital representations of the resource stored in Islandora will be recorded on the relevant Media instead of here.
	FieldDateModified *islandoraModel.EdtfField            `json:"field_date_modified,omitempty"`
	FieldDateOther    *islandoraModel.TypedTextField       `json:"field_date_other,omitempty"`
	FieldDateSeason   *islandoraModel.EntityReferenceField `json:"field_date_season,omitempty"`

	// FieldDateValid Date (often a range) of validity of a resource.
	FieldDateValid      *islandoraModel.EdtfField            `json:"field_date_valid,omitempty"`
	FieldDegreeLevel    *islandoraModel.EntityReferenceField `json:"field_degree_level,omitempty"`
	FieldDegreeName     *islandoraModel.EntityReferenceField `json:"field_degree_name,omitempty"`
	FieldDepartmentName *islandoraModel.EntityReferenceField `json:"field_department_name,omitempty"`
	FieldDescription    *islandoraModel.GenericField         `json:"field_description,omitempty"`
	FieldDigitalFormat  *islandoraModel.EntityReferenceField `json:"field_digital_format,omitempty"`
	FieldDigitalOrigin  *islandoraModel.EntityReferenceField `json:"field_digital_origin,omitempty"`
	FieldDisplayHints   *islandoraModel.EntityReferenceField `json:"field_display_hints,omitempty"`
	FieldEdition        *islandoraModel.GenericField         `json:"field_edition,omitempty"`

	// FieldEdtfDate A date without a type or relationship to the resource specified
	FieldEdtfDate         *islandoraModel.EdtfField `json:"field_edtf_date,omitempty"`
	FieldEdtfDateCaptured *islandoraModel.EdtfField `json:"field_edtf_date_captured,omitempty"`

	// FieldEdtfDateCreated Date of creation of the resource
	FieldEdtfDateCreated *islandoraModel.EdtfField `json:"field_edtf_date_created,omitempty"`
	FieldEdtfDateEmbargo *islandoraModel.EdtfField `json:"field_edtf_date_embargo,omitempty"`

	// FieldEdtfDateIssued Date of formal issuance of the resource. This includes publication dates.
	FieldEdtfDateIssued *islandoraModel.EdtfField            `json:"field_edtf_date_issued,omitempty"`
	FieldExtent         *islandoraModel.TypedTextField       `json:"field_extent,omitempty"`
	FieldFrequency      *islandoraModel.EntityReferenceField `json:"field_frequency,omitempty"`

	// FieldFullTitle If the full resource title is longer than 255 characters and you truncated it in the required Title field above, record the full title here.
	FieldFullTitle *islandoraModel.GenericField `json:"field_full_title,omitempty"`

	// FieldGenre A term or terms that designate a category characterizing a particular style, form, or content, such as artistic, musical, literary composition, etc.
	FieldGenre                *islandoraModel.EntityReferenceField `json:"field_genre,omitempty"`
	FieldGeographicSubject    *islandoraModel.EntityReferenceField `json:"field_geographic_subject,omitempty"`
	FieldHideGscholarMetatags *islandoraModel.BoolField            `json:"field_hide_gscholar_metatags,omitempty"`
	FieldHideHocr             *islandoraModel.BoolField            `json:"field_hide_hocr,omitempty"`
	FieldIdentifier           *islandoraModel.TypedTextField       `json:"field_identifier,omitempty"`
	FieldKeywords             *islandoraModel.EntityReferenceField `json:"field_keywords,omitempty"`

	// FieldLanguage Language of the resource content
	FieldLanguage          *islandoraModel.EntityReferenceField `json:"field_language,omitempty"`
	FieldLccClassification *islandoraModel.GenericField         `json:"field_lcc_classification,omitempty"`
	FieldLcshTopic         *islandoraModel.EntityReferenceField `json:"field_lcsh_topic,omitempty"`

	// FieldLinkedAgent Names of entities having some relationship to the resource, and, optionally, the relationship to the resource. If a relationship is not specified, it will be recorded as <a href="https://id.loc.gov/vocabulary/relators/att.html">Attributed Name</a> in the system's linked data representation. <br />
	// <em>Publisher/manufacturer/distributor/etc. name is recorded here, with the appropriate relationship specified.</em><br />
	// This field does not allow creating names of entities on the fly. First create a <a href="/admin/structure/taxonomy/manage/person/add" target="_blank">person</a>, <a href="/admin/structure/taxonomy/manage/family/add" target="_blank">family</a>, or <a href="/admin/structure/taxonomy/manage/corporate_body/add" target="_blank">corporate body</a>, then link it here.
	FieldLinkedAgent      *islandoraModel.TypedRelationField   `json:"field_linked_agent,omitempty"`
	FieldLocalRestriction *islandoraModel.BoolField            `json:"field_local_restriction,omitempty"`
	FieldMediaType        *islandoraModel.EntityReferenceField `json:"field_media_type,omitempty"`

	// FieldMemberOf This item's parent item in Islandora. Usually this will be a collection or compound object.
	FieldMemberOf       *islandoraModel.EntityReferenceField `json:"field_member_of,omitempty"`
	FieldModeOfIssuance *islandoraModel.EntityReferenceField `json:"field_mode_of_issuance,omitempty"`

	// FieldModel The internal-to-Islandora category of the resource. Affects how the item is displayed/viewed.
	FieldModel               *islandoraModel.EntityReferenceField `json:"field_model,omitempty"`
	FieldNote                *islandoraModel.TypedTextField       `json:"field_note,omitempty"`
	FieldOriginalTitle       *islandoraModel.GenericField         `json:"field_original_title,omitempty"`
	FieldPartDetail          *islandoraModel.PartDetailField      `json:"field_part_detail,omitempty"`
	FieldPhysicalDescription *islandoraModel.TypedTextField       `json:"field_physical_description,omitempty"`

	// FieldPhysicalForm The physical format of the original resource being described. If the resource is a physical object, the physical form is recorded here. If the resource is born-digital, the original digital form is recorded here. Details of the formats of resource representations stored in Islandora should be recorded on the relevant Media files.
	FieldPhysicalForm     *islandoraModel.EntityReferenceField `json:"field_physical_form,omitempty"`
	FieldPhysicalLocation *islandoraModel.EntityReferenceField `json:"field_physical_location,omitempty"`

	// FieldPid PID of this object in Islandora 7.x (applies to migrated objects only)
	FieldPid                   *islandoraModel.GenericField         `json:"field_pid,omitempty"`
	FieldPlacePublished        *islandoraModel.GenericField         `json:"field_place_published,omitempty"`
	FieldPlacePublishedCountry *islandoraModel.EntityReferenceField `json:"field_place_published_country,omitempty"`
	FieldPublisher             *islandoraModel.GenericField         `json:"field_publisher,omitempty"`
	FieldRecordOrigin          *islandoraModel.GenericField         `json:"field_record_origin,omitempty"`
	FieldRelatedItem           *islandoraModel.RelatedItemField     `json:"field_related_item,omitempty"`
	FieldRelation              *islandoraModel.GenericField         `json:"field_relation,omitempty"`

	// FieldResourceType The general nature or genre of the content of the resource. To describe the digital or physical format of the resource, use Form instead.
	FieldResourceType    *islandoraModel.EntityReferenceField `json:"field_resource_type,omitempty"`
	FieldRights          *islandoraModel.GenericField         `json:"field_rights,omitempty"`
	FieldSiteDisposition *islandoraModel.EntityReferenceField `json:"field_site_disposition,omitempty"`
	FieldSortBy          *islandoraModel.GenericField         `json:"field_sort_by,omitempty"`
	FieldSource          *islandoraModel.GenericField         `json:"field_source,omitempty"`

	// FieldSubject If using separate fields to record topical, geographic, name, and temporal subjects, record topical subjects here. If not splitting subjects into to different fields, all subjects can be recorded in this field.
	FieldSubject *islandoraModel.EntityReferenceField `json:"field_subject,omitempty"`

	// FieldSubjectGeneral General subjects which may include topical, geographic, temporal, and genre elements. If you wish to manage these types of subjects separately, use the more specific Subject fields.<br/><br/>Any new term added by typing it here will be added to the Subject taxonomy. If you need to create a new term in another taxonomy, do <i>Structure > Taxonomy > [the appropriate taxonomy] > Add terms</i> to add terms. You may need to save this form and reload it for your terms to be available here.
	FieldSubjectGeneral         *islandoraModel.EntityReferenceField        `json:"field_subject_general,omitempty"`
	FieldSubjectHierarchicalGeo *islandoraModel.HierarchicalGeographicField `json:"field_subject_hierarchical_geo,omitempty"`
	FieldSubjectLcsh            *islandoraModel.EntityReferenceField        `json:"field_subject_lcsh,omitempty"`

	// FieldSubjectsName Any new term added by typing it here will be added to the Person taxonomy. If you need to create a new Corporate Body or Family taxonomy term, do <i>Structure > Taxonomy > [the appropriate taxonomy] > Add terms</i> to add terms. You may need to save this form and reload it for your terms to be available here.
	FieldSubjectsName    *islandoraModel.EntityReferenceField `json:"field_subjects_name,omitempty"`
	FieldTableOfContents *islandoraModel.GenericField         `json:"field_table_of_contents,omitempty"`
	FieldTemporalSubject *islandoraModel.EntityReferenceField `json:"field_temporal_subject,omitempty"`

	// FieldThumbnail Appears as a thumbnail on “Card” views and as a representative image on article pages. This field is automatically populated by the thumbnail created on the node. But if you want to reference a thumbnail from another node, you can reference it here.
	FieldThumbnail     *islandoraModel.EntityReferenceField `json:"field_thumbnail,omitempty"`
	FieldTitlePartName *islandoraModel.GenericField         `json:"field_title_part_name,omitempty"`

	// FieldViewerOverride Select an alternate viewer, if desired for this resource.
	FieldViewerOverride *islandoraModel.EntityReferenceField `json:"field_viewer_override,omitempty"`

	// FieldWeight Enter numeric values to force a custom sort order within a collection of resources. See <a href="https://www.drupal.org/node/307797">external documentation for the <i>Weight</i> module</a>.
	FieldWeight       *islandoraModel.IntField             `json:"field_weight,omitempty"`
	Language          *islandoraModel.GenericField         `json:"language,omitempty"`
	Nid               *islandoraModel.IntField             `json:"nid,omitempty"`
	RevisionLog       *islandoraModel.GenericField         `json:"revision_log,omitempty"`
	RevisionTimestamp *islandoraModel.GenericField         `json:"revision_timestamp,omitempty"`
	RevisionUid       *islandoraModel.EntityReferenceField `json:"revision_uid,omitempty"`
	Status            *islandoraModel.BoolField            `json:"status,omitempty"`
	Title             *islandoraModel.GenericField         `json:"title,omitempty"`
	Type              *islandoraModel.ConfigReferenceField `json:"type,omitempty"`
	Uid               *islandoraModel.EntityReferenceField `json:"uid,omitempty"`
	Uuid              *islandoraModel.GenericField         `json:"uuid,omitempty"`
	Vid               *islandoraModel.IntField             `json:"vid,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Upload CSV file
	// (POST /upload)
	PostUpload(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostUpload operation middleware
func (siw *ServerInterfaceWrapper) PostUpload(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/upload", wrapper.PostUpload)

	return m
}
